ChartDataPoint:
  type: object
  properties:
    key:
      type: string
      format: string
      example: "value"
      description: "The key is the label of the value, so for example: '2024-10-01T00:00:00+02:00' => 13 or 'Groceries' => -123. For date-related charts, this is always a Atom date."
