Configuration:
  type: object
  required:
    - title
    - value
    - editable
  properties:
    title:
      $ref: '#/components/schemas/ConfigValueFilter'
    value:
      $ref: '#/components/schemas/PolymorphicProperty'
    editable:
      type: boolean
      format: boolean
      example: true
      readOnly: false
      description: "If this config variable can be edited by the user"
