ConfigValueFilter:
  type: string
  enum:
    - configuration.is_demo_site
    - configuration.permission_update_check
    - configuration.last_update_check
    - configuration.single_user_mode
    - firefly.version
    - firefly.api_version
    - firefly.default_location
    - firefly.account_to_transaction
    - firefly.allowed_opposing_types