/api/v1/configuration:
  get:
    summary: Get Firefly III system configuration values.
    description: Returns all editable and not-editable configuration values for this Firefly III installation
    operationId: getConfiguration
    tags:
      - configuration
    responses:
      200:
        description: System configuration values
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/ConfigurationArray'
/api/v1/configuration/{name}:
  get:
    summary: Get a single Firefly III system configuration value
    description: Returns one configuration variable for this Firefly III installation
    operationId: getSingleConfiguration
    tags:
      - configuration
    parameters:
      - in: path
        name: name
        required: true
        schema:
          $ref: '#/components/schemas/ConfigValueFilter'
        description: The name of the configuration value you want to know.
    responses:
      200:
        description: One system configuration value
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/ConfigurationSingle'

