ConfigurationUpdate:
  type: object
  required:
    - value
  properties:
    value:
      type: string
      format: string
      example: "1"
      description: Can be a number or a boolean. This depends on the actual configuration value.