/chart/account/overview:
  get:
    tags:
      - charts
    summary: Dashboard chart with asset account balance information.
    description: |
      This endpoint returns the data required to generate a chart with basic asset account balance information. This is used on the dashboard.
    operationId: getChartAccountOverview
    parameters:
      !correlationParameter,3
      !mandatoryDateRangeParameters,3
    responses:
      _tpl_unauthenticatedResponse,3:
      !notFoundResponse,3
      !badRequestResponse,3
      !validationErrorResponse,3
      !internalExceptionResponse,3
      "200":
        description: Line chart oriented chart information. Check out the model for more details. Each entry is a line (or bar) in the chart.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChartLine'
