Configuration:
  type: object
  properties:
    data:
      type: object
      properties:
        is_demo_site:
          type: boolean
          format: boolean
          example: true
        permission_update_check:
          type: integer
          format: int32
          example: -1
          nullable: true
          description: |
            If the user has given permission to check for updates.
            - null = never asked.
            - -1 = never asked.
            - 0 = no permission.
            - 1 = permission
        last_update_check:
          type: string
          format: date-time
          example: "2018-09-17T12:46:47+01:00"
        single_user_mode:
          type: boolean
          format: boolean
          example: true
          description: Whether other users can register.