name: "Build - API documentation"
on:
  workflow_dispatch:
    inputs:
      developrun:
        description: 'Develop run, true or false?'
        required: true
        default: 'true'
  push:
    branches:
      - main
jobs:
  build_docs:
    name: BuildDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: >-
            fileinfo
            json
            yaml
            mbstring
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
      - name: Checkout website
        uses: actions/checkout@v5
        with:
          path: 'api-docs'
          repository: 'firefly-iii/api-docs'
          #
          # "API documentation builder" token.
          #
          token: ${{ secrets.GIT_REPOS_TOKEN }}
      - name: Build documentation
        run: |
          sudo timedatectl set-timezone Europe/Amsterdam
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          export BUILD_VERSION=$(php get-version.php)
          echo "Will pull ${BUILD_VERSION} branch."
          
          cd api-docs
          git pull origin BUILD_VERSION
          cd ..
          
          echo "Running..."
          php build-api-docs.php
          
          git add dist/firefly-iii-*-v1.yaml
          git add dist/index.html
          git commit -m "🤖 Update API documentation for Firefly III"
          git push
        env:
          API_DESTINATION: ./api-docs/dist
          API_SERVER: https://demo.firefly-iii.org
          API_SOURCE_ROOT: ./api-docs/src
