name: "Build - API documentation"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_docs:
    name: BuildDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: >-
            bcmath
            curl
            fileinfo
            json
            mbstring
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
      - name: Checkout websie
        uses: actions/checkout@v4
        with:
          path: 'api-docs'
          repository: 'firefly-iii/api-docs'
      - name: Build documentation
        run: |
          php index.php
          cd api-docs
          git add firefly-iii-$API_VERSION-v1.yaml
          git add firefly-iii-$API_VERSION-v2.yaml
          git commit -m "Update API documentation for Firefly III $API_VERSION"
          git push
        env:
          API_DESTINATION: ./api-docs
          API_SERVER: https://demo.firefly-iii.org
          API_VERSION: 2.0.12
          API_ROOT: .
