name: "Build - API documentation"
on:
  workflow_dispatch:
    inputs:
      developrun:
        description: 'Develop run, true or false?'
        required: true
        default: 'true'
  push:
    branches:
      - main
jobs:
  build_docs:
    name: BuildDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: >-
            bcmath
            curl
            fileinfo
            json
            mbstring
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
      - name: Checkout websie
        uses: actions/checkout@v4
        with:
          path: 'api-docs'
          repository: 'firefly-iii/api-docs'
          #
          # "API documentation builder" token.
          #
          token: ${{ secrets.GIT_REPOS_TOKEN }}
      - name: Build documentation
        run: |
          php build-api-docs.php
          cd api-docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add firefly-iii-*-v1.yaml
          git add firefly-iii-*-v2.yaml
          git commit -m "Update API documentation for Firefly III"
          git push
        env:
          API_DESTINATION: ./api-docs
          API_SERVER: https://demo.firefly-iii.org
          IS_DEVELOP_RUN: ${{ github.event.inputs.developrun }}
          API_ROOT: .
