name: "Build - API documentation"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_docs:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts
      - name: Checkout
        run: .ci/phpstan.sh
      - name: Checkout websie
        uses: actions/checkout@v4
        with:
          path: 'api-docs'
