ConfigurationUpdate:
  type: object
  required:
    - value
  properties:
    value:
      $ref: '#/components/schemas/PolymorphicProperty'
      example: "Some-new-config var"
      description: Can be a number, a string, boolean or object. This depends on the actual configuration value.